### NumPy Library: Working with Arrays
###### Importing NumPy and Creating Arrays

In [409]:
import numpy as np

In [410]:
# Creating a list and converting it to a NumPy array
L = [1, 2, 3, 4, 5]
arr = np.array([9, 5, 6, 7, 3])
print(arr)

[9 5 6 7 3]


###### Checking the Type and Dimensions

In [411]:
print(type(arr))

<class 'numpy.ndarray'>


In [412]:
arr.ndim

1

###### Creating and Printing a 2D Array

In [413]:
arr1 = np.array([[4,5,6,7],[9,8,7,6]])
print(arr1)

[[4 5 6 7]
 [9 8 7 6]]


In [414]:
arr1.ndim

2

###### Creating and Printing a 3D Array


In [415]:
arr2 = np.array([[[7,8,9],[9,0,1]],[[9,0,1],[9,5,6]]])
print(arr2)

[[[7 8 9]
  [9 0 1]]

 [[9 0 1]
  [9 5 6]]]


In [416]:
print(arr2.ndim)

3


###### Creating and Printing a 4D Array


In [417]:
import numpy as np

# Creating a 3-dimensional array
arr2 = np.array([
    [
        [7, 8, 9],
        [9, 0, 1]
    ],
    [
        [9, 0, 1],
        [9, 5, 6]
    ]
])

# Printing the array
print(arr2)

[[[7 8 9]
  [9 0 1]]

 [[9 0 1]
  [9 5 6]]]


In [418]:
arr2.ndim

3

In [419]:
arr3 = np.array([[[[7,8,9],[9,0,1]],[[9,0,1],[9,5,6]],[[9,0,1],[9,5,6]]]])
print(arr3)

[[[[7 8 9]
   [9 0 1]]

  [[9 0 1]
   [9 5 6]]

  [[9 0 1]
   [9 5 6]]]]


In [420]:
arr3.ndim

4

###### Accessing a Specific Element

In [421]:
                                                                                                                                                                """
Accessing a Specific Element:
   - `arr2[1, 0, 2]` accesses a specific element in the 3D array.
     - The first index `1` selects the second block (since indexing starts at 0).
     - The second index `0` selects the first row within that block.
     - The third index `2` selects the third element within that row.
                                                                                                                                                                """

# Creating a 3-dimensional array
arr2 = np.array([[[7, 8, 9], [9, 0, 1]], [[9, 0, 1], [9, 5, 6]]])

# Printing a specific element from the array
print(arr2[1, 0, 2])

1


###### Converting List and Tuple to NumPy Arrays


In [422]:
list = [2,3,4,5]
a = np.array(list)
print(a)

[2 3 4 5]


In [423]:
tuple = (9,8,7,6)
b = np.array(tuple)
print(b)

[9 8 7 6]


###### Creating Ranges and Linearly Spaced Arrays

In [424]:
# Creating an array with a range of values
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [425]:
# Creating an array with a range of values from 1 to 100
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [426]:
# Creating an array with linearly spaced values between 10 and 40
c = np.linspace(10,40)
c

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

###### Creating Arrays with Zeros and Ones

In [427]:
# Creating an array filled with zeros
d = np.zeros(6)
print(d)

[0. 0. 0. 0. 0. 0.]


In [428]:
# Creating an array filled with ones
e = np.ones(7)
print(e)

[1. 1. 1. 1. 1. 1. 1.]


In [429]:
# Creating an array filled with zeros of the same shape as arr5
arr5 = np.array([9,5])
d = np.zeros(arr5)
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [430]:
# Creating an array filled with ones of the same shape as arr5
arr5 = np.array([9,5])
d = np.ones(arr5)
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###### Creating a NumPy Array Filled with a Specific Value


In [431]:
# Creating an array arr5
arr5 = np.array([9, 5, 4, 7, 3])

# Creating an array arr6 of the same shape as arr5, filled with the value 8
arr6 = np.full(arr5.shape, 8)

# Printing the array arr6
print(arr6)


[8 8 8 8 8]


In [432]:
# Checking the number of dimensions
arr6.ndim

1

###### Shape of Arrays


In [433]:
# Creating a 2D array and checking its shape
g = np.array([[4,5,6]])
g.shape

(1, 3)

In [434]:
h = np.array([[4,5,6],[9,1,2]])
h.shape

(2, 3)

###### Sorting an Array


In [435]:
# Sorting the array
arr1 = np.sort(h)
arr1

array([[4, 5, 6],
       [1, 2, 9]])

###### Performing Element-wise Operations


In [436]:
u = np.array([6,7,0,3,5])
v = np.array([8,2,4,9,1])

# Adding arrays element-wise
np.add(u,v)

array([14,  9,  4, 12,  6])

In [437]:
u = np.array([6,7,0,3,5])
v = np.array([8,2,4,9,1])

# Subtracting arrays element-wise
np.subtract(u,v)

array([-2,  5, -4, -6,  4])

###### Comparison Operations


In [438]:
# Element-wise comparison: equality
u == v

array([False, False, False, False, False])

In [439]:
# Element-wise comparison: inequality
u != v

array([ True,  True,  True,  True,  True])

In [440]:
# Modifying elements in the array
u[0] = 9
u

array([9, 7, 0, 3, 5])

###### Modifying elements in the array


In [441]:
# Creating an array and making a copy
arr9 = np.array([1,2,3,4,5,6])
x = arr9.copy()

# Modifying the original array
arr9[0] = 8

# Printing both arrays to show that the copy is not affected
print("Copied Array: ", arr9)  

print("Original Array: ", x)

Copied Array:  [8 2 3 4 5 6]
Original Array:  [1 2 3 4 5 6]


In [442]:
# Creating a view of the array
y = arr9.view()

# Modifying the original array
arr9[1] = 7

# Printing both arrays to show that the view is affected
print(arr9)
print(y)

[8 7 3 4 5 6]
[8 7 3 4 5 6]


###### Reshaping Arrays


In [443]:
# Reshaping an array to 2 rows and 5 columns
n = np.array([1,2,3,4,5,6,7,8,9,10])
n.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [444]:
# Reshaping an array to 5 rows and 2 columns
n = np.array([1,2,3,4,5,6,7,8,9,10])
n.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [445]:
# Reshaping an array to 1 row and 10 columns
n = np.array([1,2,3,4,5,6,7,8,9,10])
n.reshape(1, 10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [446]:
# Reshaping an array to 4 rows and 3 columns
n = np.array([1,2,3,2,5,6,7,5,9,10,4,32])
n.reshape(4, 3)

array([[ 1,  2,  3],
       [ 2,  5,  6],
       [ 7,  5,  9],
       [10,  4, 32]])

###### Slicing Arrays


In [447]:
# Slicing to get all elements except the last one
print(n[:-1])

[ 1  2  3  2  5  6  7  5  9 10  4]


In [448]:
# Slicing to get elements from index 1 to 2 (3rd element excluded)
print(n[1:3])

[2 3]


In [449]:
# Slicing with step to get every second element from index 1 to 4 (5th element excluded)
print(n[1:5:2])

[2 2]
